### PR TITLE
Add sad Tim Curry

### PR DESCRIPTION
**Pull request by ramiabraham**

### CODE REVIEW

**Comment by bradp** [comment]
if you want to be a dear, you should run generate_json and then do the PR there

otherwise I'll merge and do that

**Comment by bradp** [comment]
jk too late did it

**Comment by bradp** [comment]
Also just realized deployments are off, let me fix that

**Comment by bradp** [comment]
http://gifsb.in/sad/tim-curry-weep-then-die.gif

**Comment by ramiabraham** [comment]
NOOICE!

**Pull request merged**
